version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_library
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=music_library
      - DB_HOST=db
    ports:
      - "8080:8080"
    command: ["/main"]

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    entrypoint: [
      "sh", "-c",
      "sleep 10; migrate -path=/migrations -database postgres://user:password@db:5432/music_library?sslmode=disable up"
    ]
    volumes:
      - ./migrations:/migrations

volumes:
  db_data:
