definitions:
  command.Song:
    properties:
      group:
        type: string
      id:
        type: integer
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
paths:
  /songs:
    get:
      description: Get details of all songs
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get all songs
      tags:
      - songs
    post:
      consumes:
      - application/json
      description: Add a new song to the library
      parameters:
      - description: Song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/command.Song'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Internal Server Error
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add a new song
      tags:
      - songs
  /songs/{id}:
    delete:
      description: Delete a song from the library
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Internal Server Error
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a song
      tags:
      - songs
    get:
      description: Get details of a song by ID
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Internal Server Error
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get song by ID
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Update details of an existing song
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/command.Song'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Internal Server Error
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update a song
      tags:
      - songs
swagger: "2.0"
